import { createFileRoute, Link } from "@tanstack/react-router";
import { Logo } from "@/components/Logo";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/terms-of-service")({
  head: () => ({ meta: [{ title: "Terms of Service — DevANT" }] }),
  component: Terms,
});

function Terms() {
  return (
    <div className="min-h-screen bg-background py-10 px-6">
      <div className="max-w-3xl mx-auto">
        <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-6"><ArrowLeft className="size-4" /> Home</Link>
        <Logo />
        <h1 className="text-3xl font-display font-bold mt-6 mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="space-y-6 text-sm leading-relaxed text-foreground">
          <section>
            <h2 className="font-display text-xl font-semibold mt-6 mb-2">1. Acceptable Use</h2>
            <p>You agree to use DevANT only for lawful project management activities and in compliance with GitHub's Terms of Service and API Acceptable Use Policy.</p>
          </section>
          <section>
            <h2 className="font-display text-xl font-semibold mt-6 mb-2">2. AI-Generated Content</h2>
            <p>Commit summaries and tags generated by AI are provided as-is. They may contain inaccuracies and should not be relied upon for security-critical decisions.</p>
          </section>
          <section>
            <h2 className="font-display text-xl font-semibold mt-6 mb-2">3. Data Ownership</h2>
            <p>You retain all rights to your code and repository data. DevANT processes it only to provide the service.</p>
          </section>
          <section>
            <h2 className="font-display text-xl font-semibold mt-6 mb-2">4. Service Availability</h2>
            <p>We strive for high availability but do not guarantee uninterrupted service.</p>
          </section>
          <section>
            <h2 className="font-display text-xl font-semibold mt-6 mb-2">5. Limitation of Liability</h2>
            <p>DevANT is provided "as-is" without warranties of any kind. We are not liable for any indirect or consequential damages.</p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-border flex gap-4 text-xs text-muted-foreground">
          <Link to="/privacy-policy" className="hover:text-foreground">Privacy Policy</Link>
          <Link to="/" className="hover:text-foreground">Home</Link>
        </div>
      </div>
    </div>
  );
}
