/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommitsIndexRouteImport } from './routes/commits.index'
import { Route as CommitsShaRouteImport } from './routes/commits.$sha'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitsIndexRoute = CommitsIndexRouteImport.update({
  id: '/commits/',
  path: '/commits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitsShaRoute = CommitsShaRouteImport.update({
  id: '/commits/$sha',
  path: '/commits/$sha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/commits/$sha': typeof CommitsShaRoute
  '/commits/': typeof CommitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/commits/$sha': typeof CommitsShaRoute
  '/commits': typeof CommitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/commits/$sha': typeof CommitsShaRoute
  '/commits/': typeof CommitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/commits/$sha'
    | '/commits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/commits/$sha'
    | '/commits'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/commits/$sha'
    | '/commits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRoute
  CommitsShaRoute: typeof CommitsShaRoute
  CommitsIndexRoute: typeof CommitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commits/': {
      id: '/commits/'
      path: '/commits'
      fullPath: '/commits/'
      preLoaderRoute: typeof CommitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commits/$sha': {
      id: '/commits/$sha'
      path: '/commits/$sha'
      fullPath: '/commits/$sha'
      preLoaderRoute: typeof CommitsShaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRoute,
  CommitsShaRoute: CommitsShaRoute,
  CommitsIndexRoute: CommitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
