/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as InvitesTokenRouteImport } from './routes/invites.$token'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdTeamRouteImport } from './routes/projects.$projectId.team'
import { Route as ProjectsProjectIdTasksRouteImport } from './routes/projects.$projectId.tasks'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdPullsRouteImport } from './routes/projects.$projectId.pulls'
import { Route as ProjectsProjectIdMessagingRouteImport } from './routes/projects.$projectId.messaging'
import { Route as ProjectsProjectIdIssuesRouteImport } from './routes/projects.$projectId.issues'
import { Route as ProjectsProjectIdDeploymentsRouteImport } from './routes/projects.$projectId.deployments'
import { Route as ApiPublicGithubWebhookRouteImport } from './routes/api/public/github-webhook'
import { Route as ProjectsProjectIdCommitsIndexRouteImport } from './routes/projects.$projectId.commits.index'
import { Route as ProjectsProjectIdCommitsShaRouteImport } from './routes/projects.$projectId.commits.$sha'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTeamRoute = ProjectsProjectIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTasksRoute = ProjectsProjectIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPullsRoute = ProjectsProjectIdPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdMessagingRoute =
  ProjectsProjectIdMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdIssuesRoute = ProjectsProjectIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDeploymentsRoute =
  ProjectsProjectIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ApiPublicGithubWebhookRoute = ApiPublicGithubWebhookRouteImport.update({
  id: '/api/public/github-webhook',
  path: '/api/public/github-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdCommitsIndexRoute =
  ProjectsProjectIdCommitsIndexRouteImport.update({
    id: '/commits/',
    path: '/commits/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCommitsShaRoute =
  ProjectsProjectIdCommitsShaRouteImport.update({
    id: '/commits/$sha',
    path: '/commits/$sha',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/messaging': typeof ProjectsProjectIdMessagingRoute
  '/projects/$projectId/pulls': typeof ProjectsProjectIdPullsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/commits/$sha': typeof ProjectsProjectIdCommitsShaRoute
  '/projects/$projectId/commits/': typeof ProjectsProjectIdCommitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/messaging': typeof ProjectsProjectIdMessagingRoute
  '/projects/$projectId/pulls': typeof ProjectsProjectIdPullsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/commits/$sha': typeof ProjectsProjectIdCommitsShaRoute
  '/projects/$projectId/commits': typeof ProjectsProjectIdCommitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/github-webhook': typeof ApiPublicGithubWebhookRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/messaging': typeof ProjectsProjectIdMessagingRoute
  '/projects/$projectId/pulls': typeof ProjectsProjectIdPullsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/commits/$sha': typeof ProjectsProjectIdCommitsShaRoute
  '/projects/$projectId/commits/': typeof ProjectsProjectIdCommitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy-policy'
    | '/settings'
    | '/terms-of-service'
    | '/invites/$token'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/public/github-webhook'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/messaging'
    | '/projects/$projectId/pulls'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/team'
    | '/projects/$projectId/'
    | '/projects/$projectId/commits/$sha'
    | '/projects/$projectId/commits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy-policy'
    | '/settings'
    | '/terms-of-service'
    | '/invites/$token'
    | '/projects'
    | '/api/public/github-webhook'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/messaging'
    | '/projects/$projectId/pulls'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/team'
    | '/projects/$projectId'
    | '/projects/$projectId/commits/$sha'
    | '/projects/$projectId/commits'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy-policy'
    | '/settings'
    | '/terms-of-service'
    | '/invites/$token'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/public/github-webhook'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/messaging'
    | '/projects/$projectId/pulls'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/team'
    | '/projects/$projectId/'
    | '/projects/$projectId/commits/$sha'
    | '/projects/$projectId/commits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SettingsRoute: typeof SettingsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicGithubWebhookRoute: typeof ApiPublicGithubWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/team': {
      id: '/projects/$projectId/team'
      path: '/team'
      fullPath: '/projects/$projectId/team'
      preLoaderRoute: typeof ProjectsProjectIdTeamRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tasks': {
      id: '/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof ProjectsProjectIdTasksRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/pulls': {
      id: '/projects/$projectId/pulls'
      path: '/pulls'
      fullPath: '/projects/$projectId/pulls'
      preLoaderRoute: typeof ProjectsProjectIdPullsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/messaging': {
      id: '/projects/$projectId/messaging'
      path: '/messaging'
      fullPath: '/projects/$projectId/messaging'
      preLoaderRoute: typeof ProjectsProjectIdMessagingRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/issues': {
      id: '/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProjectsProjectIdIssuesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/deployments': {
      id: '/projects/$projectId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/deployments'
      preLoaderRoute: typeof ProjectsProjectIdDeploymentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/api/public/github-webhook': {
      id: '/api/public/github-webhook'
      path: '/api/public/github-webhook'
      fullPath: '/api/public/github-webhook'
      preLoaderRoute: typeof ApiPublicGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/commits/': {
      id: '/projects/$projectId/commits/'
      path: '/commits'
      fullPath: '/projects/$projectId/commits/'
      preLoaderRoute: typeof ProjectsProjectIdCommitsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/commits/$sha': {
      id: '/projects/$projectId/commits/$sha'
      path: '/commits/$sha'
      fullPath: '/projects/$projectId/commits/$sha'
      preLoaderRoute: typeof ProjectsProjectIdCommitsShaRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdDeploymentsRoute: typeof ProjectsProjectIdDeploymentsRoute
  ProjectsProjectIdIssuesRoute: typeof ProjectsProjectIdIssuesRoute
  ProjectsProjectIdMessagingRoute: typeof ProjectsProjectIdMessagingRoute
  ProjectsProjectIdPullsRoute: typeof ProjectsProjectIdPullsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdTasksRoute: typeof ProjectsProjectIdTasksRoute
  ProjectsProjectIdTeamRoute: typeof ProjectsProjectIdTeamRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdCommitsShaRoute: typeof ProjectsProjectIdCommitsShaRoute
  ProjectsProjectIdCommitsIndexRoute: typeof ProjectsProjectIdCommitsIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdDeploymentsRoute: ProjectsProjectIdDeploymentsRoute,
  ProjectsProjectIdIssuesRoute: ProjectsProjectIdIssuesRoute,
  ProjectsProjectIdMessagingRoute: ProjectsProjectIdMessagingRoute,
  ProjectsProjectIdPullsRoute: ProjectsProjectIdPullsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdTasksRoute: ProjectsProjectIdTasksRoute,
  ProjectsProjectIdTeamRoute: ProjectsProjectIdTeamRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdCommitsShaRoute: ProjectsProjectIdCommitsShaRoute,
  ProjectsProjectIdCommitsIndexRoute: ProjectsProjectIdCommitsIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SettingsRoute: SettingsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  InvitesTokenRoute: InvitesTokenRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicGithubWebhookRoute: ApiPublicGithubWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
